### ISSUE TITLE
Hapcut2 Output

### ISSUE THREAD

**Issue by yjqiu** [vibansal/HapCUT2#10]
I got another question regarding quality score in the HapCUT2 output. The field 10 in my results is all zeros and the field 11 is mostly zeros and some negative numbers. Shouldn't I expect numbers from 0-100? Or I have to run with --error_analysis_mode 1?

Thanks a lot!

**Comment by pjedge** [comment]
You are using an old binary. Please pull the latest version of the code and re-build. Those are the old style of the scores. You should expect values 0-100.
