### ISSUE TITLE
Haplotype blocks between chromosomes

### ISSUE THREAD

**Issue by conchoecia** [vibansal/HapCUT2#100]
Hello, just wondering if HapCut2 can produce haplotype blocks that span scaffolds, or if the haplotype blocks are limited to within-scaffold relationships?

I am asking because I am working on detecting a chromosomal fusion relative to the reference with Hi-C data. Thanks! I don't think that HapCut2 does this, but I wanted to check with you to be sure.

**Comment by vibansal** [comment]
The haplotype blocks generated by HapCUT2 depend on the input data. For Hi-C, if there are reads linking distant sites on a chromosome, they will be linked together in a single block. I hope that answers your question.
