### ISSUE TITLE
run_hapcut2_fosmid_data.sh fails

### ISSUE THREAD

**Issue by mathog** [vibansal/HapCUT2#101]
Just installed 1.3.2.  Tried to run run_hapcut2_fosmid_data.sh but it fails when it tries to download:

  http://www.molgen.mpg.de/~genetic-variation/SIH/Data/haplotypes.tar.gz

because ~genetic-variation no longer exists.  

Resolving www.molgen.mpg.de (www.molgen.mpg.de)... 134.76.31.205
Connecting to www.molgen.mpg.de (www.molgen.mpg.de)|134.76.31.205|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.molgen.mpg.de/~genetic-variation/SIH/Data/haplotypes.tar.gz [following]
--2020-08-07 11:52:41--  https://www.molgen.mpg.de/~genetic-variation/SIH/Data/haplotypes.tar.gz
Connecting to www.molgen.mpg.de (www.molgen.mpg.de)|134.76.31.205|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-07 11:52:42 ERROR 404: Not Found.

I looked for it on web.archive.org and while they did have the ~genetic-variation directory the SIH subdirectory was not present.  An email was sent to Margret Hoehe to see if she had an alternative download link, but I have not heard back yet.

Do you have an alternative location for these downloads?

I'm just running this to verify that the install works, if you have another test I could run that would be fine too.

Also (separate issue), the Makefile has 

HTSLIB=/usr/common/src/htslib #path/to/htslib/

that happens to be what it is on my machine, but I suspect that /usr/local/src/htslib would be more likely to work elsewhere.

**Comment by smajidian** [comment]
I think [this link](https://github.com/kuleshov/ProbHap/tree/master/data) contains the same files. The developers may confirm my suggestion.

**Comment by mathog** [comment]
Thanks for the link.   That may be the "same" data, but it is not **exactly** the same data, so the script as is will not work.  The script shows that when phasing_matrices.tar.gz is unpacked into data/NA12878_fosmid_data_original it creates files with names like chr${i}.matrix.SORTED.  But the contents of phasing_matrices.zip are chr${i}.txt both for X and (1->22).    So same number of files, but different names.   They could hold the same contents but I have no way of determining that.   Contents of one file starts like this:

```
1       3241    0       1
2       29555   0       1
3       31366   0       1
4       31647   0       1
5       40814   1       0
6       57474   1       0
7       66379   1       0
8       72865   0       1
9       76338   1       0
10      79910   1       0
11      82991   1       0

```
so it might plausibly be the same as "matrix.SORTED".

sanity_check_variant_indices.py references the data from haplotypes.tar.gz and expects names like chr4.real_refhap.phase but neither validation.zip nor vcf.zip has a name like that, instead chr4.valid.master and chr4.vcf.  

Dr. Hoehe, who is now retired, kindly forwarded the message to Dr. Duitama, who has not yet replied.

In any case, for now it seems this test method is broken and will stay that way until it is modified to use data files that are still available.

**Comment by smajidian** [comment]
Few years ago, I've run this bash script and used it for my paper. I've found the exact file (hopefully this time my guess is correct) in my hard. I've uploaded the files [here](https://github.com/smajidian/HapMC/tree/master/HapCut2_Fosmid). The files are the outputs of two `wget`s. You can create folders named `data/temp` and put these in there. Then you can run the rest of pipeline. sorry I didn't run it right now. But the bash file matches well with the names of my files. Hope it helps.

**Comment by mathog** [comment]
Prof. Duitama got back to me before you did.  He put the haplotypes.tar.gz and phasing_matrices.tar.gz files on Google drive (until such time as they can be placed permanently on some other download site, so the following link will definitely be invalid at some point)
 
   https://drive.google.com/drive/folders/1_5ycdbSEU1uIU9I_uZfJzdHJN-kB2cCr

The sh script was modified to copy those from /tmp (instead of wget), the path to HAPCUT2 adjusted, and the script was run.  It completed in ~7 minutes.  I did not note any error messages but there were a bunch of warnings at the end (see below).

After your note arrived your files were compared to the two from Prof. Duitama and they were the same.

The log file from the run ends with:

```
mean number of variants per read is 9.68 
[2020:08:11 08:36:29] building read-variant graph for phasing
[2020:08:11 08:36:29] fragments 14157 snps 49269 component(blocks) 1113
[2020:08:11 08:36:29] starting Max-Likelihood-Cut based haplotype assembly algorithm
[2020:08:11 08:36:35] starting to post-process phased haplotypes to further improve accuracy
[2020:08:11 08:36:35] starting to output phased haplotypes
[2020:08:11 08:36:35] OUTPUTTING PRUNED HAPLOTYPE ASSEMBLY TO FILE data/hapcut2_haplotypes/chrX.hap
[2020:08:11 08:36:35] N50 haplotype length is 233.33 kilobases 
[2020:08:11 08:36:35] OUTPUTTING PHASED VCF TO FILE data/hapcut2_haplotypes/chrX.hap.phased.VCF
Number of non-trivial connected components 1113 max-Degree 37 connected variants 44862 coverage-per-variant 3.053965 
WARNING: PS flag is missing from VCF. Assuming that all phased variants are in the same phase block.
(many times)
WARNING: PS flag is missing from VCF. Assuming that all phased variants are in the same phase block.

switch rate:        0.0031761189072490245
mismatch rate:      0.007207617021963254
flat rate:          0.06736048304865296
phased count:       1571733
AN50:               221032.73033707862
N50:                228146
num snps max blk:   28852

```

Those look like plausible numbers but the README.md does not say what the expected values are.  

Is this run OK?

Thanks.

**Comment by vibansal** [comment]
The numbers look okay. The HapCUT2 paper has statistics from this dataset but they may be slightly different from these numbers since the method has been updated since then: 

https://genome.cshlp.org/content/27/5/801/F2.expansion.html
https://genome.cshlp.org/content/suppl/2017/04/07/gr.213462.116.DC1/Supplemental_Fig_S2.pdf
