### ISSUE TITLE
Make error (htslib not found)

### ISSUE THREAD

**Issue by akijarl** [vibansal/HapCUT2#104]
Hello,

When I attempt `make` in the git cloned HapCUT2 repository I get the following error:
```
mkdir -p build
gcc -g -O3 -Wall -D_GNU_SOURCE -c -Wall -I/usr/common/src/htslib  hairs-src/bamread.c -lhts -o build/bamread.o
In file included from hairs-src/bamread.c:1:0:
hairs-src/bamread.h:10:10: fatal error: htslib/sam.h: No such file or directory
 #include "htslib/sam.h"
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:32: recipe for target 'build/bamread.o' failed
make: *** [build/bamread.o] Error 1
```
I have the following version of samtools installed:
```
Program: samtools (Tools for alignments in the SAM format)
Version: 1.7 (using htslib 1.7-2)
```
Does htslib need to be installed separately?

Thanks for your help.

**Comment by vibansal** [comment]
Yes, please see README for dependencies:

Requires htslib > 1.2.1. It is assumed that htslib is installed, but otherwise the path can be specified in the Makefile (HTSLIB=path). To install htslib directly from source: git clone https://github.com/samtools/htslib.git

**Comment by akijarl** [comment]
I apologize, I'm apparently blind and illiterate.
Working fine now, thank you for your quick response!
