### ISSUE TITLE
Only chr1 is phased.

### ISSUE THREAD

**Issue by zhpn1024** [vibansal/HapCUT2#108]
Dear authors,

I ran the latest version of hapcut2 for human WGS data, and only got chr1 phased results.
In debugging I found that the chrom value is always 0, and the code for chrom update no longer exist in the latest version but in previous version.
In extracthairs.c:
chrom = getindex(ht, read->chrom);
I guess this may be the cause.

Best,
Peng

**Comment by zhpn1024** [comment]
In int parse_bamfile_sorted()

**Comment by vibansal** [comment]
Thank you for pointing out this error and the fix. The fix has been pushed to master.

**Comment by olavurmortensen** [comment]
This is wonderful news, as I was having this problem. Am I correct in assuming that this fix is in [v1.3.1](https://github.com/vibansal/HapCUT2/releases/tag/v1.3.1), corrected in commit [6ef283f](https://github.com/vibansal/HapCUT2/commit/6ef283fc03091316111b7b3b9eb37e8579fd0897)?

**Comment by vibansal** [comment]
Yes. v1.3.1 has been updated to include this fix. Thanks.
