### ISSUE TITLE
Question: support for de novo SNV/INDEL variants

### ISSUE THREAD

**Issue by jbelyeu** [vibansal/HapCUT2#112]
Does HapCUT2 phase/haplotype _de novo_ SNVs/INDELs for the proband in a trio? My understanding is that it does not (from skimming manuscript/repo), just trying to make certain. Thanks!

**Comment by vibansal** [comment]
HapCUT2 phases all heterozygous variants in an individual genome, so it will phase de novo variants in the proband.

**Comment by jbelyeu** [comment]
Great, thanks (and thanks for the quick response)! How would I go about trio-aware phasing? The goal is to identify the parent of origin for each _de novo_ variant. Or would I need to phase the variants on a per-sample basis and then post-process to see which parent they came from?

**Comment by vibansal** [comment]
Phasing the child using HapCUT2 should be sufficient. The trio phasing of the genotypes (using Mendelian rules) can be used to determine which haplotype in each block came from the mother or father.

**Comment by jbelyeu** [comment]
Ok, makes sense. Thanks!
