### ISSUE TITLE
split blocks

### ISSUE THREAD

**Issue by ruqianl** [vibansal/HapCUT2#117]
Hi,

Thanks for the great tool.
I'm a bit confused from reading the methods and implementation.

is the `--split_blocks` option removed? 
With the current implementation, is there an argument that tells HAPCUT2 to split into separate blocks if the confidence is low?

Thanks,
Ruqian

**Comment by ruqianl** [comment]
I found actually just by specifying `--split_threshold`  and `--error-analysis-mode`  0 would generate splitted blocks.

**Comment by ruqianl** [comment]
Hi,

I found the logic of `--split_blocks` and `--error_analysis_mode` a bit off.

So I see that you have removed the argument `--split_blocks` and `SPLIT_BLOCKS` is now always set as 0.

Then there is no way of splitting the blocks anymore, we can only get the posterior probs as the scores but are not able to tell HapCUT2 to split it.
Is this the intended behaviour? Sorry if I have been missing something. 

Thanks,
Ruqian

**Comment by vibansal** [comment]
Sorry for the late response. The split_blocks option is not intended for normal use and has not been tested extensively, therefore, it has been removed from the command line options. You can still use it by editing the code in the file optionparser.c. The error_analysis_mode doesn't work well and is not recommended.

**Comment by ruqianl** [comment]
Thanks @vibansal , I did compile a version with --split_blocks enabled, and from my observation on my datasets, it sometimes triggers an exception, but haven't had the chance to look into that yet.
