### ISSUE TITLE
There is a bit of confusion about the hic model

### ISSUE THREAD

**Issue by YilinZhang449** [vibansal/HapCUT2#122]
Hello,
./build/extractHAIRS [options] --bam reads.sorted.bam --VCF variants.vcf --out fragment_file  --HiC 1
./build/HAPCUT2 --fragments fragment_file --VCF variants.vcf --output haplotype_output_file  --HiC 1

 Before running these two steps，what program should I use to make Hic.fastq to generate the 'reads.sorted.bam' ?

Thank you,
Yilin Zhang

**Comment by vibansal** [comment]
For HiC, the paired-end reads (fastq) should be aligned using BWA and the -5, -S, and -P options for BWA.
