### ISSUE TITLE
HAPCUT2 on Chicago reads

### ISSUE THREAD

**Issue by lloydlow** [vibansal/HapCUT2#13]
Dear Vikas,

Many thanks for responding to my question on using HAPCUT2 on Chicago reads. As per your suggestion, I will write questions/issues on the GitHub. See below for commands that I have ran for my samples. I am treating Chicago as if it's HiC data.

#Extract HAIRS
/build/extractHAIRS --hic 1 --ref file.fasta --bam sorted.bam --VCF sorted.indel.vcf --indels 1 --out fragment_file

#HAPCUT2
./build/HAPCUT2 --hic 1 --error_analysis_mode 1 --fragments fragment_file --vcf sorted.indel.vcf --output haplotype_output_file

When you suggest that I turn off trans error modelling, should I add the following option?
--new_format 1

Finally, another question I have is how to add both Chicago and HiC data for haplotyping with HAPCUT2?

Regards,
Lloyd

**Comment by pjedge** [comment]
Hi Lloyd.

here's what I would do.

#For Chicago alone
/build/extractHAIRS --maxIS <a very big number> --ref file.fasta --bam chicago.sorted.bam --VCF sorted.indel.vcf --indels 1 --out chicago_fragment_file
./build/HAPCUT2 --error_analysis_mode 1 --fragments chicago_fragment_file --vcf sorted.indel.vcf --output haplotype_output_file
# note: you could add  --new_format 1 to extractHairs here and it wouldn't affect anything.


#For Chicago + HiC
/build/extractHAIRS --new_format 1 --maxIS <a very big number> --ref file.fasta --bam chicago.sorted.bam --VCF sorted.indel.vcf --indels 1 --out chicago_fragment_file
/build/extractHAIRS --hic 1 --ref file.fasta --bam HiC.sorted.bam --VCF sorted.indel.vcf --indels 1 --out HiC_fragment_file
cat chicago_fragment_file HiC_fragment_file > combined_fragment_file
./build/HAPCUT2 --hic 1 --error_analysis_mode 1 --fragments combined_fragment_file --vcf sorted.indel.vcf --output haplotype_output_file

In the second case (mixed chicago + HiC) the chicago will be treated like normal reads with very large insert sizes, and the HiC will be modeled as potentially having trans errors (and it will try to estimate those probabilities via iterative reassembly of the combined reads)

**Comment by lloydlow** [comment]
Hi Peter,

What you would do is what I should do then in this case. I am giving it a go and see how it goes. Thanks for the speedy reply.
