### ISSUE TITLE
About maximum insert size of Hi-C data

### ISSUE THREAD

**Issue by Yutang-ETH** [vibansal/HapCUT2#130]
Hi HapCUT2 team,

First of all thank you very much for providing this beautiful tool for the community. My name is Yutang and I am a doctoral student studying complex plant genomes at ETH Zurich, Switzerland. 

I want to phase some large and heterozygous plant genomes with a reference-based phasing approach where I want to use HapCUT2 and Hi-C to assemble chromosome-level phase blocks. However, the problem I have with HapCUT2 is I don't know what is the best value for maximum insert size (maxIS) to use? By default, the value is 40 Mb, but for large plant chromosomes (minimum size > 200 Mb), I am wondering whether it makes sense to increase the value of maxIS, for example, to 100 or 200 Mb? What's the consequence of increasing maxIS to a higher value? Would this increase the number of switch errors?

By the way, we have 25x Hi-C coverage per haplotype (total 50x coverage), and I believe our Hi-C data captured some long-range interactions because from the Hi-C contact map I see many links between two chromosome arms. 

Thank you very much and look forward to your reply.

Best wishes,
Yutang

**Comment by vibansal** [comment]
Yes, using higher values of maxIS will include Hi-C read pairs for phasing that correspond to trans-interactions and increase the error rate. Please refer to the HapCUT2 paper for more details.

**Comment by Yutang-ETH** [comment]
Thank you very much for your reply. OK, I will check the paper again.

Best wishes,
Yutang
