### ISSUE TITLE
Hapcut2 crashes (segfaults) with annotated VCF

### ISSUE THREAD

**Issue by Boeinco** [vibansal/HapCUT2#14]
Hi Peter,

I was testing Hapcut2 with some annotated vcf files and it crashed with the annotated vcfs but ran fine with the other. Here is an example line from both.  The tab delimiters are in the same places, just that the info part is much longer for an annotated vcf

Normal:
1       11863   .       C       A       .       PASS    DP=19;SOMATIC;SS=2;SSC=4;GPV=1E0;SPV=3.2164E-1  GT:GQ:DP:RD:AD:FREQ:DP4:BQ:SS   0/0:.:8:8:0:0%:5,3,0,0:.:2      0/1:.:11:9:2:18.18%:3,6,2,0:.:2

Annotated:
1       11863   .       C       A       .       PASS    DP=19;SOMATIC;SS=2;SSC=4;GPV=1E0;SPV=3.2164E-1;CSQ=A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000423562|unprocessed_pseudogene|||||||||||2500|-1||HGNC|38034|||,A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000438504|unprocessed_pseudogene|||||||||||2500|-1||HGNC|38034|||,A|upstream_gene_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000450305|transcribed_unprocessed_pseudogene|||||||||||147|1||HGNC|37102|||,A|upstream_gene_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000456328|processed_transcript|||||||||||6|1||HGNC|37102|||,A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000488147|unprocessed_pseudogene|||||||||||2541|-1||HGNC|38034|||,A|upstream_gene_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000515242|transcribed_unprocessed_pseudogene|||||||||||9|1||HGNC|37102|||,A|upstream_gene_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000518655|transcribed_unprocessed_pseudogene|||||||||||11|1||HGNC|37102|||,A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000538476|unprocessed_pseudogene|||||||||||2548|-1||HGNC|38034|||,A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000541675|unprocessed_pseudogene|||||||||||2500|-1||HGNC|38034|||        GT:GQ:DP:RD:AD:FREQ:DP4:BQ:SS   0/0:.:8:8:0:0%:5,3,0,0:.:2      0/1:.:11:9:2:18.18%:3,6,2,0:.:2

Should there be such a segfault? 

Thanks,
Austin

**Comment by pjedge** [comment]
There's a hard limit on the buffer for a single line in the VCF (100000), but the problem might be somewhere else. I'm curious about the longest line in the file, can you do "wc -L annotated.vcf" and let me know the output?

**Comment by Boeinco** [comment]
My longest line is 187665, I'm guessing there might be some delimiting problem since there it segfaulted pretty quickly.

**Comment by Boeinco** [comment]
Changed the buffer to 200000 and it ran fine. Thanks!

**Comment by vibansal** [comment]
Need to use a dynamic length buffer to avoid this problem in general 

readvariant.c; char buffer[100000]
