### ISSUE TITLE
Error in `extractHAIRS': double free or corruption (fasttop)

### ISSUE THREAD

**Issue by mb2291** [vibansal/HapCUT2#18]
Hi, I encountered the following error when running extractHAIRS. Besides the required --bam, --VCF, and --out, the only other settings I used were --indels 1 and --ref. I'm running Ubuntu 14.04.

``final cleanup of fragment list: 58 current chrom (null) 0
*** Error in `extractHAIRS': double free or corruption (fasttop): 0x00000000044be190 ***
Aborted (core dumped)``

When I use the exact same files and settings with the original HapCUT it runs without error. Is there any meaningful difference between HapCUT and HapCUT2 when it comes to a single small-insert library run on an Illumina HiSeq? If not, I can just stick with HapCUT.

Thanks for your help.

**Comment by brkldj** [comment]
Hi,
I also encountered the same error. Is there any other workaround (except using HapCUT) or a fix?
Thanks!

**Comment by vibansal** [comment]
We will take a look and fix this error.

**Comment by pjedge** [comment]
Hi all,
I'm very sorry for the delay in addressing this.

As a temporary workaround, if you use the version of extractHAIRS from HapCUT project, you can 
simply use the resulting fragment file with HapCUT2 and get all the same benefits.
In theory, if you were to use the old HapCUT to assemble, I believe the difference between HapCUT and HapCUT2 for a small-insert illumina library will primarily be faster runtime and marginally better accuracy, so you wouldn't go too wrong by doing that.

It will be difficult to replicate this error without seeing your input. Can one of you please email me a VCF and BAM file for a minimum failing example (perhaps subsampling the bam file with samtools)?
Or, if the error cannot be replicated on smaller subsamples, this is valuable information as well.
My email is pedge at eng.ucsd.edu.

**Comment by vibansal** [comment]
should be fixed now
