### ISSUE TITLE
extractHAIRS generates truncated output

### ISSUE THREAD

**Issue by murraypatterson** [vibansal/HapCUT2#20]
Hi,

I ran `extractHAIRS` of HapCUT2 on a BAM file of GBs in size and it only returned tens of reads, so I generated a minimal example where the outputs of `extractHAIRS` of hapcut and HapCUT2 disagree

see it here [https://github.com/vibansal/HapCUT2/pull/19](https://github.com/vibansal/HapCUT2/pull/19)

**Comment by vibansal** [comment]
You are correct, this is due to the newer cigar operations. Thanks for reporting. We will fix it.

**Comment by pjedge** [comment]
I'll take care of this and let you know once it is fixed.

**Comment by vibansal** [comment]
Please check out the branch 'regions' for a version of the code that fixes this problem.

**Comment by vibansal** [comment]
fixed in master branch
