### ISSUE TITLE
Segmentation fault when running Hapcut2

### ISSUE THREAD

**Issue by yjqiu** [vibansal/HapCUT2#3]
I encountered the error Segmentation fault when running Hapcut2.  The last few lines of log file are listed below.

Iterating through SNPs
100.00% complete
[2017:04:29 14:42:50] no of non-trivial connected components 2624 max-Degree 5048 connected variants 173906 coverage-per-variant 22.936425
[2017:04:29 14:42:50] fragments 1799123 snps 200445 component(blocks) 2624

**Comment by pjedge** [comment]
It might be hard to diagnose the issue based on this information alone. Would it be possible for you privately share the extracted fragment file and vcf file from this run, or to determine a minimal dataset on which the segfault occurs?

**Comment by yjqiu** [comment]
I realized that there are some errors in my vcf files. It works fine after I correct them.

**Comment by pjedge** [comment]
glad you were able to resolve it!
let us know if you have further issues.
