### ISSUE TITLE
version and release software?

### ISSUE THREAD

**Issue by nellore** [vibansal/HapCUT2#30]
Are different commits of HapCUT2 effectively different versions? The installation instructions from the README recommend the user clone the repo and `make`. However, it would be great if this software were formally versioned and released so if it's included as a dependency in other software (as we'd like to!) or if someone uses the software in their paper, they can download/reference a particular version number rather than a specific commit. Maybe https://bioconda.github.io/ would help here?

Thanks for the amazing work!

**Comment by nellore** [comment]
Awesome! Thanks for the update.

**Comment by brainstorm** [comment]
Would be great to have it conda-installable 👍

**Comment by marcelm** [comment]
I’m working on a Conda recipe over at bioconda/bioconda-recipes#18350 .
