### ISSUE TITLE
extractHAIRS issue: useful fragments 0

### ISSUE THREAD

**Issue by jkreinz** [vibansal/HapCUT2#35]
I'm trying to run hapcut2 on a diploid outcrosser for 150 different samples. I've split a multisample variant vcf file into separate individuals and no matter which sample I work with, the first extractHAIR step will output "useful fragments 0" for all reads processes.

This occurs running the following command: extractHAIRS --VCF ${sample}.vcf.gz --bam ${sample}.sorted.split.dedup.rg.bam > ${sample}.frag 2> ${sample}_hairs.err

Do you have any insight on this issue? Could it be a problem with missing data or possibly not all sites within a single individual being variant (since SNPs were called population-wide)?

Thanks,
Julia

**Comment by pjedge** [comment]
Unfortunately extractHairs doesn't support gzipped VCF files yet. I'm pretty sure that's the problem.
