### ISSUE TITLE
Error while running extractHAIRS for human variance file

### ISSUE THREAD

**Issue by qingpeng** [vibansal/HapCUT2#36]
The 00-All.vcf is downloaded from ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/ directly.

Thanks!

```
$/Tools/HapCUT2/build/extractHAIRS --10X 1 --bam sample_sorted.bam --VCF  /SNP/00-All.vcf  --out unlinked_fragment_file


Extracting haplotype informative reads from bamfiles sample_sorted.bam minQV 13 minMQ 20 maxIS 1000 

VCF file /data/qzhang/SNP/00-All.vcf has 325174796 variants 
extractHAIRS: hairs-src/readvariant.c:110: parse_variant: Assertion `buffer[s] == 'G' && buffer[s+1] == 'T' && (buffer[s+2] == ':' || buffer[s+2] == '\t')' failed.
Aborted (core dumped)
```

**Comment by vibansal** [comment]
This looks like a VCF file that doesn't have a genotype field. 

extractHAIRS requires a VCF file for a single individual with genotypes (columns 9 & 10 in VCF format)

**Comment by vibansal** [comment]
Yes.

**Comment by ViriatoII** [comment]
Hello,
I have the same error.  How should those columns 9 and 10 look like?
 Here are my 9th and 10th colums (vcf file created by longranger of 10x genomics):

>GT:AD:DP:GQ:PL:BX:PS	0/1:234,22:256:99:123,0,10080:GAAGTTCAGCTGCCGT-1_60;CAAGGCCGTCAAGAGC-1_74;ACGTCAAAGCACTCAT-1_74;AACGTTGAGGGTGTGT-1_65;GCTGCAGCAATGGACG-1_74;ACTACGAGTTGCCCGA-1_70;AAAGCGGCATGTGGGA-1_74;ACGTATGAGCCAGTAG-1_60;CCAAGATTCACGGCCA-1_74;GCGCAACCAATCGCAT-1_74_70;GGAACGATCTCCAGCT-1_74_74;CGGTGTGCACACTCGG-1_70;CTCGAGGGTTAGCTCA-;GTCACAATCAACGGCC-1_74_74;GAGTCCGGTAGTCAAA-1_65;TGTACGAGTGCATAAA-1_74_70;TTAAGCGCAAATCCGT-1_60;ACTAGCATCCGTACAA-1_74_65;TACCTATTCATGTGCA-1_74;GTAAGCTGTCCAGCCA-1_74;ACGATACGTACCGTCG-1_45;TCTCGGTCAGGGTACA-1_74;AGATACCGTTCCCGAG-1_74;TCTGGAACACTGTTAG-1_60_65;ACGGTATAGTGCTGCC-1_45;TCGCTTGTCGATTCAG-1_70;CCTATTAAGGGCTTGA-1_70;AGTAGTCGTGGATAAT-1_70;GATAACCCAATAACGA-1_74;GTGCGGTCAAGTCATC-1_74_74_74;GGCGACTTCTTGTATC-1_70;CGTATGAGTGGAAAGA-1_70;GTCGAATGTTTGTTTC-1_65;CCCGAAGTCTAAGACC-1_74;CACAGTATCAGATTCG-1_70_74_74;CTACAAGTCATGAAGA-1_74;GGACGTCCACAGGAGT-1_70_74_45;ACGGTATCAACTGTTG-1_74;CGTTGAAAGTTCGCGC-1_70_60_74_70;AAGCCTACATACAGCT-1_74;CATGGCGTCCAGGGCT-1_55;GATGAAAAGAGCACCA-1_70;GGGACCTAGGGACGGA-1_60;CGAAGAGCAGAAGAGA-1_70;ACAGCTAAGATCCAGG-1_70_60;AGCAAGGTCAATCGAC-1_45;GCCAAATGTATACACC-1_74;TTTATGCTCTCTCCAG-1_45;CCCAATCCAACCTGCG-1_65;TCGAACAAGGCCTTCG-1_70;CGGTGACCACACGTGC-1_74_74;CATTCTACACGTAGGA-1_74_74;CTCAACCCAACCTGAT-1_74;AGGGAACCATATGTGC-1_74;GTATTTCAGATGTGGC-1_74;ATATGCGAGGCGAAGG-1_74_65;CATCGAACATCTGCCT-1_74;TGATTCTTCGAATGGG-1_70;CTACTTAAGCGCTCCA-1_74;AAGCGAGCAGCTTAAC-1_70;GGGTCTGGTGACCTGC-1_45_65_74;GCCGGATGTATTTCTC-1_74;CTTGGAATCAGCACGC-1_45;AGCAAGGAGTCTTGAC-1_70;AACGGAGGTTCTCTCG-1_74_65;GTAAGTCAGTTGGTAA-1_74;GATTCTTGTCTGCCTT-1_45;ACGATGTTCGTAAGTC-1_65;TAGGCATTCCCATAAG-1_55;CTGCATCTCGACTGCG-1_74;GCGCAACAGCCCGACT-1_45;CAATCCCGTGTGGCTC-1_74;GCGCTAGTCTTGACGA-1_70;CCTTTCTCAGCTTGAT-1_74;GTAGCATTCTGTGGCG-1_74;CTCAGAAAGTTACCCA-1_74;GAAGACGGTAGCTTGT-1_74;TTAAGCGCACAAGCGA-1_70;AGGAGACCACGGTAGA-1_45_74;CTAGTGACAGGATCGA-1_70;CGGACACAGGGATACC-1_45;AGTCAGTGTCATACCA-1_74;AGTACCAGTGACCTGC-1_74;CTCGATCCACGGCTAC-1_74;GAAGCAGTCCGTACCT-1_74;TTGCCGTAGATCTGCT-1_74;CTAGTCCTCTTGTTTG-1_74;GGAAGCAAGTATCGAA-1_70;GCTAGCGGTTGATCAC-1_74_70;AAGACGGCACAATCAC-1_74;TCGGAATTCATCAGGT-1_70;CTACGTCAGGGCATGT-1_74;CGATAACTCGATGTGT-1_70;TCGGGACCAGCACACC-1_74;AAGATAGAGAGCGTGT-1_74;AAGGAGCAGTCCTATG-1_70;CCCGGAATCCTAGCTC-1_74_74_74;GAATGAAGTTGCCATA-1_60;ATAGCGTAGGTGATAT-1_74;CTCATTATCTTCGACC-1_74;CTCTGTGAGATTCACC-1_74;ATTCTACGTGTAACCT-1_74_74;ATCGGATCATCTGCCT-1_74;CTATTTGTCCGCGTTT-1_45;AGCTCTCAGTGAATGT-1_65;CAGAATCGTTAGTTGC-1_45;CTCTTTCAGTCTAGCT-1_45;TGGTTAGTCTTAGTCT-1_74;TGCGGGTCATAGGTCT-1_74;GTCGGTGAGATAAGTC-1_74;ACCAACACAACGGGAT-1_74;TCGCTACCATCCAACA-1_74;AATCGGTTCGCTAGCG-1_70;CGCCGAACAAGCACGA-1_45;TGGAGCCAGGTCGCTC-1_45;GATAACCTCCAACAAC-1_70;CGAGAAGCATCGCATA-1_65;AGAGTGGGTGATGTAA-1_45_70;GTCGACGTCATAAGCC-1_74;GGCTGGTGTCGGTGCT-1_74;CCATCACTCATAAAGG-1_74;TTGAGGTAGAGCCGTA-1_45;ACTGTAGAGTCTGTCA-1_74;AGTTACGAGTTACCCA-1_65;ACGTACAGTCGAACAG-1_74;CAGGAGACACCAACAT-1_70;CACATAGAGACTAGGC-1_60;AGGTCCGAGATATGGT-1_45;CAGCCGAAGTGCGTGA-1_74;AAGCGAGCACTTCTTA-1_74;CGTCTCACAGTCAAGG-1_45;CATCACCCACGCAACC-1_74_60;CCAACTCTCTCTAGGA-1_74;AAACGGGTCGACGTAT-1_70_45;AGATTGCTCTCAAACG-1_74;CGCAGACCATACGGAG-1_70;ATGTGTGGTTGCAGCC-1_74;ATCACCCAGCTTCGCG-1_60;TCCGGTTGTCCGGATC-1_74;CAGTGTAAGTCGCCGT-1_70;ATTCCATTCGCTTATT-1_74;GGATGGAAGGAAGGTA-1_70_65;TCCTCGACAGCATGTT-1_55;ACACGTATCATGCTGA-1_74_74_74;

Thank you,
Ricardo

**Comment by pjedge** [comment]
This is strange. It seems like that file should be valid.
Are there any lines in the VCF that don't have GT in the FORMAT field?

**Comment by MeHelmy** [comment]
Have the same error example of column 9 and 10:
```
GT:GQ:DP	1/1:60:2
GT:GQ:DP	0/1:64:2
GT:GQ:DP	0/1:60:2
```

**Comment by maryawood** [comment]
Hello, I am getting this same assertion failure error on the latest release (v1.1) of the software. My format fields in my VCF are all one of the following three formats, so the `GT` field is always first:

```
GT:AD:DP:GQ:PL:VT
GT:FREQ:VT
GT:VT
```

Is there anything else I should look into that might be causing this problem?

**Comment by vibansal** [comment]
This should only happen if the 'GT' field is not formatted correctly. If you can share the VCF file, it would be easy to find the line that's causing the problem. Otherwise, I would recommend validating the VCF file using GATK or vcf-validator.

**Comment by maryawood** [comment]
Thank you for your response! After some further troubleshooting on my own, I discovered that this variant had an exceptionally long (> 1 million character) info field resulting from decomposition of a variant using the software vt. Modifying the info field resolved this problem.
