### ISSUE TITLE
 output column 2 and 3, what is the values "2" mean?

### ISSUE THREAD

**Issue by Jeff-Liu9453** [vibansal/HapCUT2#41]
Hi, 
I have a similar question from #32 . I got some SNP report that  the value of 2nd and 3rd column are "2". 
like 
615793  0       1
615794  1       2
615795  1       0
or
583127  0       1
583128  2       1
583129  0       1
What is that "2" mean? 
I look forward to get the reply . Thank you! 

and I also have another question about use pacbio mode in extractHAIRS. I can ran single small contig(about 5000bp) and get well result. But when I ran the longest contig(about 220000bp) 
I got an error as below:
*** Error in `bin/HapCUT2/build/extractHAIRS': malloc(): memory corruption: 0x0000000001d8f600 ***
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f0daa14a7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f0daa15513e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_calloc+0xba)[0x7f0daa157dca]
bin/HapCUT2/build/extractHAIRS[0x409666]
bin/HapCUT2/build/extractHAIRS[0x40ad13]
bin/HapCUT2/build/extractHAIRS[0x40c2b6]
bin/HapCUT2/build/extractHAIRS[0x40cbab]
bin/HapCUT2/build/extractHAIRS[0x40fa1c]
bin/HapCUT2/build/extractHAIRS[0x403255]

It look like there is some problems with memory. Is there have any suggestion for me?
I look forward to get the reply . Thank you!

**Comment by vibansal** [comment]
The output alleles follow the VCF alleles format. '2' means the 2nd alternate allele in the VCF file. 

Is it possible for you to share a small dataset where we can reproduce the memory error ? That will allow us to debug the code.
