### ISSUE TITLE
haplotype blocks no header after spliting with prune_haplotype.py

### ISSUE THREAD

**Issue by linzhangTuesday** [vibansal/HapCUT2#42]
Hi Peter,
Thank you very much for previous suggestions about splitting haplotypes from Pacbio derived reads using prune_haplotype.py. It devided ~4000 blocks into ~6000 blocks after splitting based on switch error. However, I found the splitted spot has no header information for the following block, which make the downstream kind of difficult cuz these ones don't come up with separate header metrics such as total span, or phased SNV numbers. An example is as below
BLOCK: (from split)
348     -       -       Chr1      137421  T       A       0/1:255,0,255:48:11     0       19.00   19.00
May I ask if there's any suggestions regarding that?
Many Thanks!

**Comment by pjedge** [comment]
Hi, those block metrics are computed by HapCUT2. Unfortunately, the block-splitting script currently does not re-compute the metrics for new smaller blocks. We might add this functionality in later, but for the time being a custom script would be necessary.

**Comment by vibansal** [comment]
This should be fixed now (master branch).
