### ISSUE TITLE
snakemake with 4 fastq files

### ISSUE THREAD

**Issue by mictadlo** [vibansal/HapCUT2#46]
Hi,
We have got 4 Hi-C Fastq files 
`N_Ben_HiC2.R1.fq.gz  N_Ben_HiC2.R2.fq.gz` and
`N_Ben_HiC4.R1.fq.gz  N_Ben_HiC4.R2.fq.gz`

How is it possible to run your snakemake workflow with those above files?

Furthermore, our assembly is based on pure PacBio data.

Thank you in advance,

Michal

**Comment by pjedge** [comment]
Hi Michal,

Before answering your original question:

HapCUT2 was not designed to phase de novo assemblies and we can't make statements about the feasibility or efficacy of this. It seems that you have both PacBio data and Hi-C data and want to combine them into a phased, diploid assembly. There is a new method designed specifically for phased diploid assemblies combining Hi-C and PacBio reads:
([FALCON-phase paper](https://www.biorxiv.org/content/early/2018/05/21/327064))
[FALCON-phase paper](https://github.com/phasegenomics/FALCON-Phase)

I would first attempt to use this method for your case.
If for some reason this doesn't work and you need to try with HapCUT2, I'd look at this thread, where we address this same issue: https://github.com/vibansal/HapCUT2/issues/33

Anyway, back to your original question:
This is sort of hard to answer without more knowledge of your specific experiment. I assume that R1 and R2 correspond to "first read in pair" and "second read in pair".
Then you could combine the fastq containing the R1s and combine the fastqs containing the R2s and then you'll have two fastq files you can use.
