### ISSUE TITLE
error in extractHAIRS

### ISSUE THREAD

**Issue by yaosl** [vibansal/HapCUT2#48]
I run extractHAIRS always show *** Error in `/home/yaosl/software_yao/HapCUT2-master/build/extractHAIRS': malloc(): memory corruption: 0x000000000d2bace0 *** and
/opt/gridview//pbs/dispatcher/mom_priv/jobs/2144.admin.SC: line 5:  1838 Aborted                 (core dumped) /home/yaosl/software_yao/HapCUT2-master/build/extractHAIRS --pacbio 1 --bam /home/yaosl/pacbio_sequel_2017/02.phasing_method/0
5.phasing/AC_phasing/01.raw/AC_results/tissue_calassify/root_1/root_1.all_A.header.sorted.bam --VCF /home/yaosl/pacbio_sequel_2017/02.phasing_method/05.phasing/AC_phasing/01.raw/AC_results/tissue_calassify/root_1/root_1.all_A.vcf --ref /
home/yaosl/pacbio_sequel_2017/02.phasing_method/05.phasing/AC_phasing/01.raw/AC_results/tissue_calassify/A_ref.fa --out  /home/yaosl/pacbio_sequel_2017/02.phasing_method/05.phasing/AC_phasing/01.raw/AC_results/tissue_calassify/root_1/hapcut_test/test1/root_1.A.fragment_file
I don not know how to deal with this problem.

**Comment by vibansal** [comment]
It has taken a long time, but this bug should be fixed now (see branch realignment).

**Comment by yaosl** [comment]
Really thanks for your hard work and help, I will check now.


Sincerely,
Shengli Yao







At 2019-01-05 03:31:28, "Bansal Lab" <notifications@github.com> wrote:


It has taken a long time, but this bug should be fixed now (see branch realignment).
