### ISSUE TITLE
generate fasta of haplotype

### ISSUE THREAD

**Issue by conchoecia** [vibansal/HapCUT2#49]
Hi All,

Just curious if you have a tool to easily generate a fasta file of phased haplotype blocks using a reference and the output of HapCUT2? I haven't been able to find one in your docs and wanted to ask before writing something to do this.

Thanks,
Darrin

**Comment by conchoecia** [comment]
edited title to be more clear

**Comment by pjedge** [comment]
Unfortunately, there isn't a single-step way to do this. But, you can convert the output of hapcut2 to VCF (see hapcut2vcf, linked in the readme) and then use bcftools consensus to generate the phased fasta using the VCF and fasta reference.

**Comment by conchoecia** [comment]
Thank you-
