### ISSUE TITLE
HAPCUT2 accuracy issues

### ISSUE THREAD

**Issue by yuzhang0327** [vibansal/HapCUT2#5]
Dear professor,

Thanks very much for your advice. I am not sure whether I calculated the HAPCUT2 accuracy with wrong method?
I am not sure what the column 11 means as nan occupied half of the result?
Attached is part of the result produced by HAPCUT2, as we used C57/PWK mouse HiC data as input, we expected majority value of column 2 vs. 3 should be 1:0, but the result attached here varies a lot, the accuracy is just about 75% (The total number of 1:0 divided by total number of rows for column 2 vs. 3)
[test.txt](https://github.com/vibansal/HapCUT2/files/975143/test.txt)

Best,
Yu

**Comment by pjedge** [comment]
The Nan values are unexpected. This is a bug.
What exact options did you use to run extractHAIRS and HapCUT2?
Can you make a small subsample of your input that produces the same problems and share them with me?
Regarding your method of calculating accuracy, it seems like a valid approach at first glance.

**Comment by yuzhang0327** [comment]
Dear professor,

Here is the command I used to run extractHAIRS and HapCUT2.
extractHAIRS --HiC 1 --bam /data4/yu/soft/hapcut2/hapcut2-master/hic_separated/hic.REF_chrX.bam --VCF /data4/yu/soft/hapcut2/hapcut2-master/vcf_mm9/chrX.vcf --qvoffest 64 --out fragment_fileX &

HAPCUT2 --fragments fragment_fileX --vcf /data4/yu/soft/hapcut2/hapcut2-master/vcf_mm9/chrX.vcf --output output1.hap --hic 1 --qv_offset 64 --htrans_data_outfile {output.model_file}

Due to the bytes limitation of the files, I sent the subsamples of my input through email.

Best,
Yu

**Comment by pjedge** [comment]
I'm closing this issue, we can continue to discuss in the other open issue.
