### ISSUE TITLE
Confused about --indels

### ISSUE THREAD

**Issue by conchoecia** [vibansal/HapCUT2#50]
Hi Peter et al-

I am a bit confused about the `--indels` option based on the command line options description: `--indels <0/1> : extract reads spanning INDELS, default is 0, variants need to specified in VCF format to use this option`.

Am I right in my understanding that `--indels 1` should only be used if the `--VCF <indels_only.vcf>` contains only indels? So, `--indels 0` would be used with `--VCF <SNPs_only.vcf>`?

I have both Chicago, HiC, and 10X data, so I am imagining a use case like so where I could run `extractHAIRS` for each data type on both indels and SNPs, like so for Chicago data here: 

```
#For Chicago
/build/extractHAIRS --new_format 1 --maxIS <a very big number> --ref file.fasta --bam chicago.sorted.bam --VCF sorted.indels_only.vcf --indels 1 --out chicago_fragment_file
/build/extractHAIRS --new_format 1 --maxIS <a very big number> --ref file.fasta --bam chicago.sorted.bam --VCF sorted.SNPs_only.vcf --indels 0 --out chicago_fragment_file
```

taken from your example https://github.com/vibansal/HapCUT2/issues/13#issuecomment-314005275

**Comment by vibansal** [comment]
"--indels 1" should be used for the VCF file that contains both SNPs and indels. extractHAIRS will only need to be run once.

**Comment by conchoecia** [comment]
Excellent. Thank you!
