### ISSUE TITLE
Run is taking longer than expected based on manuscript stats.

### ISSUE THREAD

**Issue by conchoecia** [vibansal/HapCUT2#51]
I have a run for ~500,000 SNPs in a 150Mbp genome with greater than 100x coverage HiC + Chicago data that is taking a long time to run. So far it has been 52 hours, which is much longer than I would expect given stats above and the runtimes described in the hapcut2 manuscript. Does it seem like something is wrong, or should I let the program finish running? Thank you!

Here is the script I ran:

```
reference="final_assembly.fa"
chibam="chicago/chic.sorted.bam"
hicbam="hic/hic.sorted.bam"
vcf="GLO64_libs_to_reference.snps.filt.manual.vcf"
/usr/local/bin/HapCUT2/build/extractHAIRS --new_format 1 --maxIS 200000 --ref ${reference} --bam ${chibam} --VCF ${vcf} --indels 0 --out hapcut/chicago_fragment_file
/usr/local/bin/HapCUT2/build/extractHAIRS --hic 1 --ref ${reference} --bam ${hicbam} --VCF ${vcf} --indels 0 --out hapcut/HiC_fragment_file
cat hapcut/chicago_fragment_file hapcut/HiC_fragment_file > hapcut/combined_fragment_file
/usr/local/bin/HapCUT2/build/HAPCUT2 --hic 1 --error_analysis_mode 1 --fragments hapcut/combined_fragment_file --vcf ${vcf} --output hapcut/haplotype_snps_output_file.hapcut
```

And here is the output to the terminal where the process currently sits:

```
[2018:09:05 10:00:32] fragment file: hapcut/combined_fragment_file
[2018:09:05 10:00:32] variantfile (VCF format):GLO64_libs_to_reference.snps.filt.manual.vcf
[2018:09:05 10:00:32] haplotypes will be output to file: hapcut/haplotype_snps_output_file.hapcut
[2018:09:05 10:00:32] solution convergence cutoff: 5
[2018:09:05 10:00:32] QVoffset: 33

[2018:09:05 10:00:32] Calling Max-Likelihood-Cut based haplotype assembly algorithm
[2018:09:05 10:00:58] read 453269 variants from GLO64_libs_to_reference.snps.filt.manual.vcf file
Number of non-trivial connected components 6585 max-Degree 3092 connected variants 437376 coverage-per-variant 104.118308
[2018:09:05 10:01:07] fragments 10424378 snps 453269 component(blocks) 6585
[2018:09:05 10:01:12] processed fragment file and variant file: fragments 10424378 variants 453269
```

**Comment by pjedge** [comment]
It does seem like it should have finished already. Was HapCUT2 built from a recent commit? If the build is older than roughly a year there could be an issue with the combination of --hic 1 and --error_analysis_mode 1. Did you get a warning to stderr about that ("WARNING: Switch error quality scores are not intended for use with Hi-C data. Scores will be left blank")? Also, could you run with --verbose 1 and show the full stdout+stderr? This will print updates to stderr about what iteration it's in, and we can see if it's making progress or if it's stuck in a loop / some other bug.

**Comment by conchoecia** [comment]
Hi Peter - I just built it last week from a fresh pull. I'll run it on `--verbose 1` and let you know how it is going in a day or so. Thanks!

**Comment by pjedge** [comment]
After double checking, I'm sure that you should be seeing the warning "WARNING: Switch error quality scores are not intended for use with Hi-C data. Scores will be left blank.".
It should be one of the first things printed to stderr. I'm not sure why it's not being printed here, but please double check the commit that you are using.

**Comment by conchoecia** [comment]
Hi Peter - here is the output from `git log -1`. I'm not sure of the exact commit number though.

```
Author: Peter Edge <edge.peterj@gmail.com>
Date:   Wed Jul 11 16:54:00 2018 -0700

    bug fix in calculate_haplotype_statistics for triallelic variants
```

It turns out that running hapcut2 on my data took around 50 hours of walltime. So, when I submitted this issue and close it to run `--verbose 1`, it was only a few hours away from finishing. Let me know if you would like me to paste anything from the run.

**Comment by pjedge** [comment]
Could you paste the full stdout/stderr from the run that completed? Or email it to me?

**Comment by conchoecia** [comment]
Sure - I restarted the job to captures stderr and stdout to a file since we now know that it works. I will send the results in a few days when it finishes again.

**Comment by pjedge** [comment]
thanks. I also want to know if the output haplotypes have values in the "switch quality" column (column 10), or if they're blank (".")
