### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by smajidian** [vibansal/HapCUT2#54]
Dear Peter
I intend to compare my algorithm to HapCUT for a fragment matrix. This kind of data was used in RefHap, AltHap, and ProbHap. This data has been generated before by [Geraci](http://bioalgo.iit.cnr.it/rehap/), and I get it directly from him:
> Geraci, Filippo. "A comparison of several algorithms for the single individual SNP haplotyping reconstruction problem." Bioinformatics 26.18 (2010): 2217-2225.

A part of matrix is as following:
> acgtga------------------------
atgtg-----------------ctgtga--
attt-atcagcggtc-----------aag-
ttgt--------------------------
att---ggcac-------------------
---tga------------------------

Each row is a read containing just SNP loci. The "-"s in a row are those SNP loci which are not included in that read.  The column number of matrix equals to haplotype length. 

I found out that HapCUT needs a Bam and/or VCF file.  Does HapCUT support such file as input? 
I asked this issue from [HapCHAT](https://github.com/AlgoLab/HapCHAT/issues/4) and WhatsHap team, but I'm not successful yet. 

It will be appreciated if you tell me a clue for doing so.
Best regards,
Sina.

**Comment by vibansal** [comment]
HapCUT2 actually uses a fragment matrix as input. It is generated by the program extractHAIRS but can be generated using other means.

**Comment by smajidian** [comment]
Dear Dr. Bansal
Thanks a lot.
