### ISSUE TITLE
Requirements for 10x barcoded reads

### ISSUE THREAD

**Issue by olavurmortensen** [vibansal/HapCUT2#58]
It is not entirely clear to me what is required of a 10x barcoded BAM file. The documentation in the readme ([here](https://github.com/vibansal/HapCUT2#10x-genomics-linked-reads)) doesn't really say anything. The [10x recipe](https://github.com/vibansal/HapCUT2/tree/master/recipes/10X) says aligned barcoded 10x reads with the BX tag, which is quite clear. I'm guessing as long as it follows the description on the [10x page about barcoded BAMs](https://support.10xgenomics.com/genome-exome/software/pipelines/latest/output/bam) it should be fine, which should be the case for all BAMs produced by 10x pipelines such as LongRanger (?).

Is my understanding correct? Would be great if it was more clear in the 10x section of the README.

**EDIT:**

By the way, I just made an issue for this because I didn't know where to pose this question. Hope this is ok.

**Comment by pjedge** [comment]
Hi,
Sorry it isn't more clear.
Yes, the only requirement should be the BX tag. It is expected/recommended that the standard 10X pipelines are used to prepare the BAM, but it should work as long as the reads have the BX tag.
