### ISSUE TITLE
Hapcut2 reads limit

### ISSUE THREAD

**Issue by yuzhang0327** [vibansal/HapCUT2#6]
Dear professor,

I am sorry to bother you again, but I still account for reads limit as before even when you use new scripts (the new data set has more than 2200000 reads), so I wonder whehter you can increase the reads limit more? 
FYI, here is the former description of reads limit problem:

'I have tried the HAPCUT2 with a PWK/C57BL mouse HiC data. When I used the fragment files generated by extractHAIRS, it always report errors as below:
Too many nodes allocated: 262144.
So I reduced the fragments files to just 260000 rows ( I have ~1000000 rows for the fragment file), the HAPCUT2 works well. So I wonder whether it is reasonable to split the fragment files to run HAPCUT2? If not, how can I modified the script to adjust HAPCUT2 to accept more than 1000000 reads one time?'

Best,
Yu

**Comment by pjedge** [comment]
Hi Yu,

There shouldn't be any limit on the number of reads. What is the output you are getting?

best
Peter

**Comment by pjedge** [comment]
Also, just checking, but did you re-run both the extractHairs and HapCUT2 steps after pulling and building the newest version of the code?

**Comment by yuzhang0327** [comment]
Dear professor,

The report error is as below:
Too many nodes allocated: 262144.

I re-run the extractHairs and HapCUT2 steps already. I also tried to pick up 1551657 reads from all 2675381 reads, it works well then, but still can't run with all 2675381 reads.

Best,
Yu

**Comment by pjedge** [comment]
Hi Yu,

The limit was a limit on number of SNPs while determining connected components, not reads. It is now set to over 536 million.

Did you build again (with "make") after pulling the most recent code? I think you're using an old binary. I'm pretty sure that's the only possible way you could get the specific error message and number you reported. 

thanks,
Peter

**Comment by pjedge** [comment]
Hi Yu, can you confirm that the issue went away when you re-compiled the code?
