### ISSUE TITLE
read gzipped VCF files or exit with appropriate error message

### ISSUE THREAD

**Issue by vibansal** [vibansal/HapCUT2#60]

**Comment by cipher2k5** [comment]
Is it possible to clarify the difference between switch error rate and mismatch rate?  I see different definitions in the your publication  and on the Hapcut2 repository. https://www.biorxiv.org/content/biorxiv/early/2017/05/08/135384.full.pdf
"a switch error was defined as two or more SNPs in a row
flipped. Second, a mismatch error was defined as a heterozygous
SNP whose phase was incorrectly inferred."

On the hapcut2 git repository, i see the following definition:
"A switch error is defined as a position where the phase is switched from that of the previous heterozygous SNV, when compared to the reference haplotype. 
Two switch errors in a row are instead counted as a mismatch error, a single position where the phase differs from the reference haplotype."

If you can point to any cartoon illustrating these, that would be awesome!!
Thanks
Tarun

**Comment by vibansal** [comment]
program checks if VCF file ends in '.gz' and exits with error message
