### ISSUE TITLE
Short switch vs mismatch error

### ISSUE THREAD

**Issue by cipher2k5** [vibansal/HapCUT2#61]
Is it possible to clarify the difference between switch error rate and mismatch rate? I see different definitions in the your publication and on the Hapcut2 repository. https://www.biorxiv.org/content/biorxiv/early/2017/05/08/135384.full.pdf
"a switch error was defined as two or more SNPs in a row
flipped. Second, a mismatch error was defined as a heterozygous
SNP whose phase was incorrectly inferred."

On the hapcut2 git repository, i see the following definition:
"A switch error is defined as a position where the phase is switched from that of the previous heterozygous SNV, when compared to the reference haplotype.
Two switch errors in a row are instead counted as a mismatch error, a single position where the phase differs from the reference haplotype."

If you can point to any cartoon illustrating these, that would be awesome!!
Thanks
Tarun

**Comment by vibansal** [comment]
Both definitions are the same. See illustration below: 

![image](https://user-images.githubusercontent.com/4740729/53676867-fc5b2400-3c5c-11e9-8a75-00d4c386f6ae.png)

**Comment by cipher2k5** [comment]
Thanks for the clarification!
