### ISSUE TITLE
High missing SNPs for Pacbio

### ISSUE THREAD

**Issue by smajidian** [vibansal/HapCUT2#62]
Hi
Firstly, I generated two fasta files from ~1Mb reference genome which differs only in some nucleotides (SNPs) using [haplogenerator.py](https://github.com/EhsanMotazedi/Haplosim). Then I combined two mentioned files in a fasta file:
```
cat genome.fa.fai 
hap_1	100140	8	100140	100141
hap_2	100140	100157	100140	100141
```
So, I have a diploid genome containing 2679 heterozygous SNPs.  
Then, I generated reads using [PBSIM](https://github.com/pfaucon/PBSIM-PacBio-Simulator) with average coverage of 100 for described genome.fa.

I called the variants using [Clairvoyante](https://github.com/aquaskyline/Clairvoyante) results in 7402 variants. In order to examine extractHAIRS, I removed non-truth positions. So, `var_het.vcf` contains part of true SNPs (2477  SNPs).

I run this
```
${hapcut2_path}extractHAIRS --pacbio 1 --mbq 1 --mmq 1  --bam sorted.bam --VCF var_het.vcf --out frag.txt  --ref ../ref/ref.fa

Extracting haplotype informative reads from bamfiles sorted.bam minQV 1 minMQ 1 maxIS 1000 

VCF file var_het.vcf has 2477 variants 
vcffile var_het.vcf chromosomes 1 hetvariants 2477 2477
reading fasta index file ../ref/ref.fa.fai ... fasta file ../ref/ref.fa has 1 chromosomes/contigs

contig chr21 length 1001940
reading reference sequence file ../ref/ref.fa with 1 sequences
chr21 1001940 GATCCACCCGCCTTGGCCTCCTAAAGTGCT
read reference sequence file in 0.01 sec
reading sorted bamfile sorted.bam 
processing reads mapped to chrom "chr21" 
```
The first three lines of frag.txt

```
2 S1_hap2_27496 2193 10011 2199 1 444444
2 S1_hap2_19245 2194 0 2196 11 444
1 S1_hap2_18199 2193 000 444
```
It seems that more than 2000 first variants are missed in fragment file, which can also be seen in HapCUT2 output.
```
majid001@pevzner:/mnt/scratch/majid001/pb2/8_1/var/old$ grep "BLOCK" out.hap 
BLOCK: offset: 2196 len: 17 phased: 16 SPAN: 3998 fragments 2
BLOCK: offset: 2234 len: 25 phased: 24 SPAN: 5958 fragments 6
BLOCK: offset: 2311 len: 2 phased: 2 SPAN: 83 fragments 2
BLOCK: offset: 2327 len: 151 phased: 150 SPAN: 44926 fragments 1908
```
By using `samtools depth` most of the positions are with good coverage. Would you please provide me a clue to handle this issue?

**Comment by pjedge** [comment]
1. Can you share a couple lines from var_het.vcf (maybe the first few records, and also a few around the 2193th variant)?
2. Can you share an example of a BAM record covering the region that seems to be "ignored"?
3. If you're interested in calling and phasing SNVs from pacbio data, you might want to try our new tool [Longshot](https://github.com/pjedge/longshot) (but I also want to resolve this issue and make sure it is not a problem with extractHAIRS/HapCUT2.)

**Comment by smajidian** [comment]
Thanks for your fast response. Here are some details.
``` 
$ head -n 15 var_het.vcf
chr21   64796   .       C       CAAAA   3       .       .       GT:GQ:DP:AF     0/1:3:193:0.1813
chr21   342585  .       A       AC      3       .       .       GT:GQ:DP:AF     0/1:3:218:0.1697
chr21   560571  .       T       TT      3       .       .       GT:GQ:DP:AF     0/1:3:191:0.1623
chr21   588888  .       A       AC      3       .       .       GT:GQ:DP:AF     0/1:3:181:0.1823
chr21   795434  .       A       AC      3       .       .       GT:GQ:DP:AF     0/1:3:208:0.1635
chr21   800678  .       A       AC      3       .       .       GT:GQ:DP:AF     0/1:3:201:0.1791
chr21   903289  .       GA      G       3       .       .       GT:GQ:DP:AF     0/1:3:218:0.1055
chr21   2108    .       G       T       430     .       .       GT:GQ:DP:AF     0/1:430:137:0.3431
chr21   2520    .       T       G       321     .       .       GT:GQ:DP:AF     0/1:321:150:0.2800
chr21   2536    .       A       C       315     .       .       GT:GQ:DP:AF     0/1:315:147:0.2857
chr21   3208    .       A       C       999     .       .       GT:GQ:DP:AF     0/1:999:164:0.2927
chr21   3270    .       A       C       405     .       .       GT:GQ:DP:AF     0/1:405:155:0.2903
chr21   3277    .       C       A       330     .       .       GT:GQ:DP:AF     0/1:330:165:0.3333
chr21   3291    .       G       T       315     .       .       GT:GQ:DP:AF     0/1:315:194:0.1701
chr21   3342    .       G       T       296     .       .       GT:GQ:DP:AF     0/1:296:166:0.2771

$ sed -n 2190,2195p var_het.vcf
chr21   901535  .       A       C       387     .       .       GT:GQ:DP:AF     0/1:387:236:0.1992
chr21   902181  .       C       A       285     .       .       GT:GQ:DP:AF     0/1:285:211:0.1848
chr21   902765  .       C       A       278     .       .       GT:GQ:DP:AF     0/1:278:207:0.2319
chr21   905139  .       A       C       236     .       .       GT:GQ:DP:AF     0/1:236:208:0.1587
chr21   905470  .       A       C       273     .       .       GT:GQ:DP:AF     0/1:273:211:0.1564
chr21   905500  .       A       C       156     .       .       GT:GQ:DP:AF     0/1:156:194:0.1340
```
I extracted  a part of the Bam file. Then, I run extractHAIRS:
```
$sed -n 1500,1500p var_het.vcf
chr21   651728  .       T       G       363     .       .       GT:GQ:DP:AF     0/1:363:189:0.1429
$sed -n 2100,2100p var_het.vcf
chr21   862330  .       T       G       147     .       .       GT:GQ:DP:AF      0/1:147:225:0.1422

$samtools view -b  -o a.bam sorted.bam chr21:651728-862330
${hapcut2_path}extractHAIRS --pacbio 1 --mbq 1 --mmq 1    --bam a.bam --VCF var_het.vcf --out frag_part.txt  --ref ../../ref/ref.fa
```
The output,`frag_part.txt ` is empty. I've uploaded [this part of bam](http://webpages.iust.ac.ir/s_majidian/hapcut2_issue/a.bam),  [vcf](http://webpages.iust.ac.ir/s_majidian/hapcut2_issue/var_het.vcf), and [reference](http://webpages.iust.ac.ir/s_majidian/hapcut2_issue/ref.fa) files.
We can look at it in IGV!
![screenshot 2019-03-06 at 10 39 15](https://user-images.githubusercontent.com/41860044/53871289-45fc9380-3ffc-11e9-8c2a-4b1cf9c18d82.png)


That's a fresh paper! Thanks for suggestion. I'm installing it.

**Comment by smajidian** [comment]
Now, I'm using [Longshot](https://github.com/pjedge/longshot). The mentioned error is not arising. If it happens another time, I will let you know.
