### ISSUE TITLE
extractHairs pointer error

### ISSUE THREAD

**Issue by psur9757** [vibansal/HapCUT2#64]
I am trying to run HapCUT2 for a PacBio dataset. I started with squashed ploidy genome and followed the steps listed in https://github.com/vibansal/HapCUT2/issues/52

Once I have the bam (from minimap/samtools) and the vcf (from GATK) files, I run the following script. The ref option was added to extractHAIRS because it gives an error without it.

hapcut2.pbs
```
#!/bin/bash
#PBS -P OSR
#PBS -N hapcut2
#PBS -l select=1:ncpus=4:mem=64GB
#PBS -l walltime=20:00:00
#PBS -e logs/hapcut2.err
#PBS -o logs/hapcut2.out

cd $PBS_O_WORKDIR

module load hapcut/2
module load python/3.7.2

extractHAIRS --pacbio 1 --ref ref/canu3.fa --bam results/minimap/canu3_sorted.bam --VCF results/gatk/recal1_filtered_variants.vcf --out results/hapcut2/canu3_frags

HAPCUT2 --ea 1 --fragments results/hapcut2/canu3_frags --VCF results/gatk/recal1_filtered_variants.vcf --output results/hapcut2/canu3_ref

python3.7 /usr/local/hapcut/2/utilities/prune_haplotype.py -i results/hapcut2/canu3_ref -o results/hapcut2/canu3_ref.pruned --min_mismatch_qual 30 --min_switch_qual 30
```

The error file ([hapcut2.err](https://github.com/vibansal/HapCUT2/files/2986430/hapcut2.txt)) is attached and here is the main problem:
`*** glibc detected *** extractHAIRS: free(): invalid pointer: 0x0000000004366790 ***`

Thank you.

**Comment by vibansal** [comment]
Can you try the new version of the code: https://github.com/vibansal/HapCUT2/releases/tag/5a6f5df 
This should fix the problem with extracthairs.

**Comment by psur9757** [comment]
Yes that fixed the error. I have a couple other questions.
1. Are there any parameters you recommend changing or testing in the above script?
2. How do I get a fasta file from either the hapcut2 output or the pruned output for downstream analysis?

Thank you for your help.

**Comment by pjedge** [comment]
1. The parameters look good to me (although phasing assembled contigs is an "unofficial" use case).
2. At this time the recommended strategy would be to convert the HapCUT2 output to VCF (see readme) and after that you can insert the phased variants over a reference with ```bcftools consensus```. I'm not sure about the behavior of bcftools consensus for unphased variants, so do use this with care.
