### ISSUE TITLE
ExtractHAIRS error

### ISSUE THREAD

**Issue by marizazh** [vibansal/HapCUT2#65]
Hi!
I'm trying to phase de novo genome assembly created with combination of Hi-C reads and PacBio polished with Illumina reads. I have aligned to this assembly PacBio reads (which are my .bam file), variant calls from Illumina reads aligned to this de novo assembly and assembly itself. When I try hapcut2 it crushes at extractHAIRS step with following message:
```45228 Segmentation fault      (core dumped) /gpfs0/apps/x86/bin/extractHAIRS --pacbio 1 --indels 1 --bam /mnt/qnap/work/phasing/gm12878/second_try/gm78_dedup.bam --ref /mnt/qnap/work/phasing/de_novo_genomes/gm12878/GM12878.hs-PB-HiC.fasta --VCF /mnt/qnap/work/phasing/gm12878/second_try/gm12878_denovo.vcf --out gm78_fragment_file```
Can you please give any suggestions regarding this? I have already verifies all input files and didn't find any truncated or corrupted.

Thanks!

**Comment by vibansal** [comment]
Can you try the new version of the code: https://github.com/vibansal/HapCUT2/releases/tag/5a6f5df

We will push this update to the master branch shortly.

**Comment by marizazh** [comment]
Thanks a lot! It worked!
