### ISSUE TITLE
Understanding HapCut2 blocks

### ISSUE THREAD

**Issue by psur9757** [vibansal/HapCUT2#67]
Hello HapCut2 Team,

After assembly and polishing, I run Haplomerger2 on my genome, this I expect separates my alleles into reference and alternate. Now I run both reference and alternate with HapCut2 which creates haplotype blocks. To get sequences I run fgbio HapToVcf and then bcftools consensus. This is as recommended here: https://github.com/vibansal/HapCUT2/issues/64#issuecomment-475357400

Since the vcf file from HapCut2 blocks has two alleles, I run bcftools consensus for both alleles separately. This means I end up with 4 fasta files total and I don’t know which ones to combine to get the two haplotypes.

Here is my situation: The fungi I work on has two nucleus each with haploid genome. During sequencing they get mixed together so I was trying to get phased genome to get to each of the original haploid genome. I know this is not the HapCut2 official function nor will the blocks be perfect. I am trying to get as good as I can. 

Any recommendations would be most appreciated. Thank you. 

Best Regards,
Priyanka

**Comment by pjedge** [comment]
Hi Priyanka,
The phased VCF should be diploid. You should form a consensus of the first alleles with the reference sequence, and then form a consensus of the second alleles with the reference. I think what you're saying is you don't know which fasta file to use BCFtools consensus with, because you have two? The answer is, I'm not sure but it should be whichever one has the reference alleles according to the VCF you ran HapCUT2 with.

**Comment by psur9757** [comment]
Hello Peter,

I made a diagram which hopefully explains the situation better.
![haplotypes](https://user-images.githubusercontent.com/37357172/55995484-f3e41780-5cf7-11e9-8231-9f1adb6bf5df.jpg)
 
I am trying to figure out which of these 4 to discard or combine. Thank you.

Best Regards,
Priyanka

**Comment by pjedge** [comment]
I'm sorry, I still don't quite understand.
before running hapcut2, you should have:
- a single haploid fasta file
- a diploid VCF with respect to that haploid fasta showing where the variants are.

**Comment by psur9757** [comment]
When I assemble my PacBio reads using Canu, I get a diploid assembly (~170M). Then I use Haplomerger2 to get a haploid (~85M) assembly (reference) but it also gives an alternate set. I use the reference to create a VCF using GATK and then run HapCut2. Using fgbio and bcftools consensus, I get two fasta sequence files based on the two alleles. I repeat this process with the alternate set, so another two fasta files. This is how I end up with four instead of two.

**Comment by pjedge** [comment]
You should just do it using the first reference, since that's the more confident haploid assembly, correct?

**Comment by psur9757** [comment]
Yes I suppose that makes sense. I was a bit hesitant about throwing half the data. Thank you for your help.
