### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by MeHelmy** [vibansal/HapCUT2#68]
Followed the installation instruction

` cd HapCUT2/`
Then
`make`
But I have this error.

```
hairs-src/readvariant.c:5:51: error: htslib/hts.h: No such file or directory
hairs-src/readvariant.c: In function ‘count_variants’:
hairs-src/readvariant.c:18: warning: unused variable ‘n’
make: *** [build/readvariant.o] Error 1
```

Thanks

**Comment by pjedge** [comment]
Looks like HTSlib did not build. The Make file tries to pull in the submodules if necessary and then build them, but this could have failed. What happens if you do 

```
make clean
git submodule init
git submodule update
make
```

**Comment by MeHelmy** [comment]
error changes
`
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:57:19: error: bzlib.h: No such file or directory
cram/cram_io.c:61:18: error: lzma.h: No such file or directory
.....
ake[1]: *** [cram/cram_io.o] Error 1
make[1]: Leaving directory `.source/htslib-1.9'
make: *** [/source/htslib-1.9/libhts.a] Error 2
`

Is there a version for hapcut on conda?

**Comment by pjedge** [comment]
Hi, we're hoping to add HapCUT2 to conda soon.
in the meantime, installing the "zlib" and "xz" packages should ensure that samtools builds correctly.

**Comment by MeHelmy** [comment]
Thanks,
Installed the lib, yet have the error:
`hairs-src/readvariant.c:5:51: error: htslib/hts.h: No such file or directory
hairs-src/readvariant.c: In function ‘count_variants’:
hairs-src/readvariant.c:18: warning: unused variable ‘n’
make: *** [build/readvariant.o] Error 1`

Meanwhile:
`ls submodules/htslib/*.h`
I see only
`submodules/htslib/hfile_internal.h  submodules/htslib/version.h`

**Comment by pjedge** [comment]
that's really weird, because that header file should have been downloaded with the submodule.
This implies that the submodule didn't clone correctly.

Does samtools work if you install curses?

Also, what operating system / linux distro are you using?

**Comment by MeHelmy** [comment]
Linux version:
`Linux version 2.6`
regarding courses (I can only ` conda install -c anaconda ncurses `) which is not helping here.

for the point that they did not clone correctly:
I removed totally the ole clone and recloned it 
`git clone git@github.com:vibansal/HapCUT2.git`
`cd HapCUT2/
make`

Error:

mkdir -p build
gcc -g -O3 -Wall -D_GNU_SOURCE -Isubmodules/samtools -Isubmodules/htslib -c hairs-src/bamread.c -o build/bamread.o
gcc -g -O3 -Wall -D_GNU_SOURCE -c hairs-src/hashtable.c -o build/hashtable.o
gcc -g -O3 -Wall -D_GNU_SOURCE -c hairs-src/readvariant.c -o build/readvariant.o
hairs-src/readvariant.c:5:51: error: htslib/hts.h: No such file or directory
hairs-src/readvariant.c: In function ‘count_variants’:
hairs-src/readvariant.c:18: warning: unused variable ‘n’
make: *** [build/readvariant.o] Error 1`
`

**Comment by colindaven** [comment]
Are you mixing conda and tool compiling ? This always gives me problems, since I use conda on shells by default.

I would reset everything and try again after installing ncurses with your system package manager.

**Comment by MeHelmy** [comment]
@colindaven Thank you unfortunately, I do not have `sudo` privilege. So I install packages etc ... using conda

**Comment by pjedge** [comment]
I found out that there was indeed a problem related to a missing include in the Makefile in the latest release. Can you let me know if you still have this problem?

**Comment by MeHelmy** [comment]
So I re-cloned it and compiled it.  it compiled right this time.
