### ISSUE TITLE
HapCutToVcf issue

### ISSUE THREAD

**Issue by yuzhang0327** [vibansal/HapCUT2#7]
Dear professor,

I tried to use HapCutToVcf to convert hap file to vcf file, there are 2 kinds of heter information in the last column, one is '0/1' while the other is '0|1', I am not sure whether they have different means or I can just take them as the same?

Best,
Yu

**Comment by pjedge** [comment]
'0/1' means unphased while '0|1' means phased. They are not equivalent.
https://samtools.github.io/hts-specs/VCFv4.2.pdf
