### ISSUE TITLE
Combining data from separate vcf files

### ISSUE THREAD

**Issue by mdem7705** [vibansal/HapCUT2#70]
Hi HapCUT2 team,

I have a question around how best to combine data from two separate vcf files that belong to the same genome that will work with HapCUT2.

I have assembled my genome with CANU from PacBio reads, polished it with Pilon and haplophased it with HaploMerger2. I have both 150bp illumina reads and 250bp illumina reads for this genome, and I have been able to use both sets of reads to do all steps thus far.

Now I have gone through the GATK pipeline and generated two vcf files for the same genome using HaplotypeCaller (one file each from aligned 150bp and 250bp illumina reads) and I need to combine them into a single file to use with hapCUT2. I was thinking to use MergeVCFs to do this (https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.2.0/picard_vcf_MergeVcfs.php) but I have some concerns that it might change the format too much. Is there a preferred method to combine them that you can suggest?

Thanks in advance for your help!

**Comment by pjedge** [comment]
Hi, I'm not sure the best way to do this. The only thing I can say is whatever the strategy, try to ensure the variants are as accurate as possible, and genotyped correctly.
