### ISSUE TITLE
HapCUT2 is dependent on pysam -- but which version?

### ISSUE THREAD

**Issue by olavurmortensen** [vibansal/HapCUT2#72]
To run `utilities/LinkFragments.sh` you need to install `pysam`, I didn't see that dependency mentioned anywhere. I installed `pysam v0.15.2` via [Conda](https://anaconda.org/bioconda/pysam), and this seemed to work fine, but it would be good to know exactly which version this was built and tested on.

**Comment by pjedge** [comment]
Thanks for pointing this out -- me migrated over to the linkfragments script for 10X datasets a while after the paper was published. I'm not sure what version of pysam was originally used. But, we have a set of tests for linkfragments (test_LinkFragment.py) and as long as it passes those, then we can be pretty confident that the version of pysam will not cause problems. We are in the process of implementing a new UX for extractHairs/HapCUT2 and we will be putting it on conda after we've tested it, so when that time comes the pysam dependency will be managed.

**Comment by olavurmortensen** [comment]
@pjedge Nice to hear you're packaging it with conda. Thanks for the rapid and helpful response :smiley:
