### ISSUE TITLE
Leading white-space in "PD" format line

### ISSUE THREAD

**Issue by olavurmortensen** [vibansal/HapCUT2#74]
In the following line, the `FORMAT` line for the `PD` annotation is printed to the header:
https://github.com/vibansal/HapCUT2/blob/master/hapcut2-src/printhaplotypes.c#L162

There is a minor problem though. I've encountered that tools don't like the leading white-space in the string, `" phased Read Depth"`, and will actually cause a fatal error.

This is a minor issue, because the fix is easy, I just have to fix the header line. At the same time though, this is a super easy issue to fix in the code.

**Comment by vibansal** [comment]
Thanks for pointing out this error. The code has been fixed.

**Comment by olavurmortensen** [comment]
Excellent, thank you.
