### ISSUE TITLE
HIC_repair.py error

### ISSUE THREAD

**Issue by tommathers** [vibansal/HapCUT2#76]
Hi,

I am trying run HapCUT2 with HIC (~220x coverage) and ONT long read data. I am basically following the recipe in the example snakemake file.

After mapping each end of the HIC data seperatly and sorting with samtools I keep getting an error with the HIC_repair.py script:

`(HapCUT2) [tmathers@-HPC bash HapCUT2]$  python /nbi/software/testing/HapCUT2/git11062019/src/HapCUT2/utilities/HiC_repair.py -b1 HIC_r1.sorted.bam -b2 HIC_r2.sorted.bam -o hic_repaired.bam -m 20
Performing Hi-C repair...
Traceback (most recent call last):
  File "/nbi/software/testing/HapCUT2/git11062019/src/HapCUT2/utilities/HiC_repair.py", line 398, in <module>
    repair_chimeras(args.bamfile1, args.bamfile2, args.outfile, args.min_mapq)
  File "/nbi/software/testing/HapCUT2/git11062019/src/HapCUT2/utilities/HiC_repair.py", line 265, in repair_chimeras
    assert(f1.qname == f2.qname)
AssertionError`

Any idea why this might be happening? BWA and samtools version are the same as in the snakemake file. 

Is this step essential or can I safely skip to the extract hairs step?

Thanks,

Tom.

**Comment by pjedge** [comment]
Hi,
The issue here is that the qname-sorted bamfiles for the two read ends have
an entry where the qnames for the paired reads do not match up. I'm not
sure why it would happen, because sorting each file by qname should make it
so that each corresponding pair of reads occur at the same record number in
the file. You should find out where and why that is happening.

**Comment by tommathers** [comment]
Hi,

Thanks for this. I double checked and realised I had missed the sort by name flag when I mapped the R1 and R2. Worked fine when I sorted them as the program expects! I have marked this closed.

Thanks for your help and apologies for the daft error. 

Tom.
