### ISSUE TITLE
hapcut2 what next

### ISSUE THREAD

**Issue by rob123king** [vibansal/HapCUT2#81]
I have run Hapcut2 and have a VCF file. 
1) I can't see in the VCF where it has assigned the snp to one haplotype or the other, any ideas where that information is kept? 
I can see it in the other hapcut output file but not the VCF which seems wrong. 

2) I assume can separate the two haplotypes in vcf to two separate files so can have two tracks for each haplotype in a browser. 

3) Any ideas how to produce a phased block chromosome image using the VCF or hapcut2 file. Assume someone must have done this before.

4) If I can separate out the haplotypes form the VCF then I can use this to create the two reference haplotype sequences, hoping there is a way to separate this without me having to right something.

**Comment by conchoecia** [comment]
Hi rob123king-

If you take a look at the VCF file the unphased sites have a tag at the end with a slash `0/0:172:161,11:161:6298:11:414:0,-19.8451,-493.274`. If the site is phased it has a pipe character `1|0:196:156,40:636:100:172`.

`1|0` means that the allele in col3 is on hap1 and the allele in col4 is on hap0. `0|1` means that the allele in col3 is on hap0 and the allele in col4 is on hap1.

(2) You could write a GFF file or a bed file for each haplotype to put into IGV? It would just take a little parsing.

(3) Something custom in matplotlib?

(4) If you want to generate a haplotype for each fasta then try `bcftools consensus -H ${INDEX}`
