### ISSUE TITLE
prune_haplotype.py format change?

### ISSUE THREAD

**Issue by mdem7705** [vibansal/HapCUT2#84]
Hi hapCUT2 team,

I am having problems running the pruned vcf file that is output from hapCUT2 with fgbio's HapCutToVcf. I brought the issue up with them but they think the error may be the result of a change in format from print_haplotype.py, so I wanted to check in with you and see what you thought.

Please refer here for the fgbio issue I raised:  [https://github.com/fulcrumgenomics/fgbio/issues/541](url)

As mentioned in a previous issue here #73 I'm running hapCUT2 on my contigs separately because they are highly heterozygous, just in case that affects anything. 

Here is the code I am trying to run:

```
module load hapcut/2-1.1

extractHAIRS --pacbio 1 --bam Sc0000001.bam --ref Sc0000001.fa --VCF Sc0000001.vcf --out Sc0000001.frags
HAPCUT2 --ea 1 --fragments Sc0000001.frags --VCF Sc0000001.vcf --output Sc0000001.blocks

python3.7 /usr/local/hapcut/2/utilities/prune_haplotype.py -I Sc0000001.blocks -o Sc0000001.pruned --min_mismatch_qual 30 --min_switch_qual 30

java -jar /usr/local/fgbio/0.9.0-snapshot/fgbio-0.9.0-snapshot.jar HapCutToVcf -v  Sc0000001.vcf -I Sc0000001.pruned -o Sc0000001_phased.vcf 
```

My reference vcf and pruned files are here: 
[hc2vcf.zip](https://github.com/vibansal/HapCUT2/files/3753988/hc2vcf.zip)
I am using this version of hapCUT2: https://github.com/vibansal/HapCUT2/releases/tag/5a6f5df

Thanks for your help!

**Comment by vibansal** [comment]
It seems that the error is due to the header of the output block not being updated by the prune_haplotype.py script. The person who wrote this script is currently unavailable. I can try to fix it but I will need the input file Sc0000001.blocks.

**Comment by mdem7705** [comment]
Okay, I have uploaded 3 blocks files. These are 3 contigs which I have tried to run using the same code. The first 2 contigs (Sc0000000 and Sc0000001) are both having this error. For some reason the third one (Sc0000002) does not, so I included it for your reference. 

[Sc0000000.blocks.gz](https://github.com/vibansal/HapCUT2/files/3791420/Sc0000000.blocks.gz)
[Sc0000001.blocks.gz](https://github.com/vibansal/HapCUT2/files/3791421/Sc0000001.blocks.gz)
[Sc0000002.blocks.gz](https://github.com/vibansal/HapCUT2/files/3791422/Sc0000002.blocks.gz)

**Comment by nh13** [comment]
Related to https://github.com/fulcrumgenomics/fgbio/issues/541

**Comment by nh13** [comment]
@vibansal is this still an issue?

**Comment by vibansal** [comment]
I just pushed a fix to the master branch. Thanks for raising it again.

**Comment by vibansal** [comment]
Closing this issue.
