### ISSUE TITLE
Combine Hi-C and WGS for HapCUT2

### ISSUE THREAD

**Issue by yjqiu** [vibansal/HapCUT2#9]
I hope to combine Hi-C and WGS for phasing. @pjedge mentioned previously that I can use the example of hic+longread. I checked the workflow but still have some questions to check.

The idea is to run extracHAIRs on two bam files separately and then concatenate two fragment files. The parameter for WGS/longread is --nf 1, and the parameter for HiC is --hic 1. The parameter to run HapCUT2 is --hic 1, which is the same as running Hi-C alone. Am I correct here? 

Doesn't HapCUT2 estimate htrans model using both WGS and Hi-C data if I run this way?

**Comment by pjedge** [comment]
When you use the --nf (new format) option in extractHAIRS on the normal WGS reads it generates fragments in a format with extra columns that is compatible with HiC fragments so you can combine files with HiC fragments successfully without a parse error, but it marks the reads as "normal reads" with no trans errors.

So it should work to use the hic+longreads pipeline. using the --hic option in HapCUT2 is perfectly compatible with having "normal reads" (or long reads, 10x) mixed in. It'll only factor in h-trans probabilities for those reads marked as HiC in the file, and when it iterates and re-estimates h-trans probabilities it'll only base it off the HiC reads.

**Comment by yjqiu** [comment]
That makes perfect sense. Thanks a lot!

**Comment by fritzsedlazeck** [comment]
@pjedge sorry I dont completely understand it. 
I want to combine 10x + long reads to phase some snps. I see from the readme that Pacbio and 10x requires certain parameters and even an extra step after the extract hairs. 
So how could I combine both techs to phase SNPs?
Thanks
Fritz

**Comment by pjedge** [comment]
Hi, I understand it isn't very straightforward. In the future we intend to simplify the usage into a single step, including combining multiple read technologies. For your use case, this should do:
```./build/extractHAIRS --10X 1 --bam tenX.sorted.bam --VCF variants.VCF --out unlinked_fragment_file
python3 utilities/LinkFragments.py --bam tenX.sorted.bam --VCF variants.VCF --fragments unlinked_fragment_file --out linked_fragment_file
./build/extractHAIRS --pacbio 1 --nf 1 --bam pacbio.sorted.bam --VCF variants.VCF --out pacbio_fragment_file
cat linked_fragment_file pacbio_fragment_file > combined_fragment_file
./build/HAPCUT2 --nf 1 --fragments linked_fragment_file --vcf variants.vcf --output haplotype_output_file```

**Comment by fritzsedlazeck** [comment]
@pjedge awesome thanks for the rapid answer. 
Cheers
Fritz
