### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by FrickTobias** [vibansal/HapCUT2#91]
I think the README file could be a bit out of date and clarifying some things could hopefully reduce the number of issues posted having to do with user malpractice.

I've jotted down some things I've come across which to me seem like they could have been more true to an earlier version, or at least not clear enough for me to understand it fully.
- **output file description name:** The README states the output will be written to an `out.phase.VCF` file, but it seemingly describes the `out.phase` file.
- **`- -` phases:** Some phases are written as `- -` while according to the numbered list, these fields can only take either `1` or `0`. From reading the text below this seems to be a result from whenever `--discrete_pruning 1` isn't used but I think it could be good to expand the numbered list to also include `-` as a possible value.
- **`********` rows:** I'm running into the output having rows which are only written as 8 `*` in a row and cannot find any documentation what these rows mean.

**Comment by vibansal** [comment]
Many thanks for pointing out these issues. I have updated and cleaned up the README file. The phased output block file description has been moved to a separate file.

**Comment by FrickTobias** [comment]
Thanks a lot! Just one last thing I noticed, my files have 12 columns rather than the 11 which are documented.

```
 cat phase-file | head
BLOCK: offset: 261 len: 4231 phased: 2278 SPAN: 1886352 fragments 2645
261	-	-	chr1	789130	T	A	0/1:13:11,2:11:381:2:62:-0.087102,0,-19.4507	1	.	3.68	2
262	0	1	chr1	789445	T	A	0/1:12:10,2:10:370:2:50:-0.566989,0,-13.7097	0	.	26.22	3
265	1	0	chr1	790564	C	A	0/1:17:8,9:8:296:9:260:-1.4864,0,-12.391	0	.	100.00	2
268	1	0	chr1	792473	C	T	0/1:19:8,10:8:296:10:361:-0.160973,0,-12.8297	0	.	29.21	1
310	1	0	chr1	820143	C	T	0/1:7:5,2:5:159:2:74:-0.44739,0,-5.28299	0	.	35.51	2
311	1	0	chr1	820169	T	G	0/1:7:5,2:5:147:2:74:-0.162553,0,-7.48213	1	.	36.76	2
317	0	1	chr1	821264	A	T	0/1:14:12,2:12:406:2:74:-0.212649,0,-16.9445	1	.	22.46	2
318	0	1	chr1	822248	T	A	0/1:12:8,3:8:258:3:86:-0.662489,0,-12.0419	0	.	22.00	1
325	1	0	chr1	823414	C	G	0/1:14:12,2:12:432:2:74:-0.485248,0,-27.4007	0	.	100.00	4
```

**Comment by vibansal** [comment]
I will update this. Column 12 is the coverage of the variant in the fragment file (input to HapCUT2).

**Comment by FrickTobias** [comment]
Great, thanks!
