### ISSUE TITLE
Valid [GT] accepted by extractHAIRS

### ISSUE THREAD

**Issue by agroppi** [vibansal/HapCUT2#92]
Before extractHair I filter my vcf with : 

`vcffilter -f "MLEAC > 0" $OUT_DIR/$file | grep -vw "\./[0-2]" > $OUT_DIR/$SAMPLE_NAME"_filtered.vc`f"

==> filtering out all ./0 or ./1 or ./2 in the GT field

But in some vcf I found GT such as 2/3 ...

So it would be better to filter out all GT fields not accepted by extractHAIRS

Could you pleased give me a list of the GT fields accepted by extractHAIRS ?

**Comment by agroppi** [comment]
Problem solved the space value is 
[0,1,2]/[0,1,2]
or 
[0,1,2]|[0,1,2]
Right ?

**Comment by vibansal** [comment]
Yes, the code can handle up to three alleles (0,1,2) but has additional filters. I have copied the description from the code below: 

Each VCF entry must have a diploid genotype (GT) field consisting of two alleles in the set {0,1,2} separated by either / or |.
