### ISSUE TITLE
Duitama et al. data download

### ISSUE THREAD

**Issue by robinweide** [vibansal/HapCUT2#93]
Hi all, 

The link to the reference-set of haplotypes from Duitama et al. returns a 404. Could you please update the link or make the data available otherwise? 

Thank you so much for your time and the wonderful tools!

**Comment by vibansal** [comment]
This dataset was not generated by us but by a group at Max Planck: https://www.molgen.mpg.de/157216/Diploid-Genomics. Please contact them for updating the link

**Comment by smajidian** [comment]
A part of Duitama's data is provided [here](https://github.com/kuleshov/ProbHap/tree/master/data).
