### ISSUE TITLE
Hi-C with bwa mem -5SPM

### ISSUE THREAD

**Issue by conchoecia** [vibansal/HapCUT2#94]
I noticed that in some of your recipes for using Hi-C data that you map reads individually and then repair the mates. One recommended way to map Hi-C data is to use `bwa mem -5SPM ref.fa read1.fq read2.fq`, and I believe that this preserves mate information. A quick inspection of the bam file reveals that most of the reads are paired (`samtools view -f 1 myfile.bam`). 

Do you think that I need to do any other processing before extracting hairs? I ran picard MarkDuplicates for good measure, as that is what you did in your example.

**Comment by vibansal** [comment]
You are correct. The -5SPM option works well for Hi-C reads without further processing. We have used it as well. The recipes in the repository need to be updated.

**Comment by conchoecia** [comment]
Great - thank you. That is my only question, so I will close this issue.

By the way, I have a new Snakemake recipe PR coming your way in a few days. This script can be used for any combination of read types, and automatically adapts if one or more read types are missing.
