### ISSUE TITLE
output vcf headers

### ISSUE THREAD

**Issue by conchoecia** [vibansal/HapCUT2#95]
Hello,

I can't find any documentation for how to format the HAPCUT2 vcf output headers. Specifically, I'm interested in what needs to be in the `##INFO` fields, and what options I need to specify for `##phasing`? I have one HAPCUT2 vcf file per chromosome, and want to merge and sort them all.

Thank you-

**Comment by vibansal** [comment]
Currently, the header file of the VCF output by HapCUT2 only adds the PS, PQ and PD fields if they  are not present. The header file should be the same for every chromosome.
